# 1. project test
project-add:
	@mocha project-add.js

project-deal:
	@mocha project-deal.js

project: project-add project-deal

table-add: project-add
	@mocha table-add.js

table-deal:
	@mocha table-deal.js
